name = "agent-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Enable Workers AI
[ai]
binding = "AI"

# Enable KV Namespace
[[kv_namespaces]]
binding = "AGENT_CACHE"
id = "2f3279ec01b34630ab398fa30900cb49"
